development:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: herbs_development
  pool: 5
  username: herbs
  password: hd03J8glsJnmDl4DFD

test:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: herbs_test
  pool: 5
  username: herbs
  password: hd03J8glsJnmDl4DFD

production:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: herbs_production
  pool: 5
  username: herbs
  password: hd03J8glsJnmDl4DFD
